// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanTempFiles() {
  return window['go']['main']['App']['CleanTempFiles']();
}

export function CreateArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateArchive'](arg1, arg2, arg3);
}

export function CreateItem(arg1, arg2) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2);
}

export function FileAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileAction'](arg1, arg2, arg3);
}

export function GetDriveData(arg1) {
  return window['go']['main']['App']['GetDriveData'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetFileAssociations() {
  return window['go']['main']['App']['GetFileAssociations']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetRangerData(arg1, arg2) {
  return window['go']['main']['App']['GetRangerData'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsDriveAuthenticated() {
  return window['go']['main']['App']['IsDriveAuthenticated']();
}

export function LoginGoogle(arg1, arg2) {
  return window['go']['main']['App']['LoginGoogle'](arg1, arg2);
}

export function OpenAssociationsFile() {
  return window['go']['main']['App']['OpenAssociationsFile']();
}

export function OpenFileCustom(arg1, arg2) {
  return window['go']['main']['App']['OpenFileCustom'](arg1, arg2);
}

export function OpenSettingsFile() {
  return window['go']['main']['App']['OpenSettingsFile']();
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2);
}

export function ReadFilePreview(arg1) {
  return window['go']['main']['App']['ReadFilePreview'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UnzipItem(arg1) {
  return window['go']['main']['App']['UnzipItem'](arg1);
}
