// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanTempFiles():Promise<string>;

export function CreateItem(arg1:string,arg2:boolean):Promise<void>;

export function FileAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDriveData(arg1:string):Promise<main.RangerState>;

export function GetDrives():Promise<Array<string>>;

export function GetFileAssociations():Promise<Record<string, string>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetOS():Promise<string>;

export function GetRangerData(arg1:string,arg2:boolean):Promise<main.RangerState>;

export function GetSettings():Promise<main.AppSettings>;

export function IsDriveAuthenticated():Promise<boolean>;

export function LoginGoogle(arg1:string,arg2:string):Promise<string>;

export function OpenAssociationsFile():Promise<void>;

export function OpenFileCustom(arg1:string,arg2:string):Promise<void>;

export function OpenSettingsFile():Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function ReadFilePreview(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function UnzipItem(arg1:string):Promise<void>;

export function ZipItem(arg1:string):Promise<void>;
