// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckoutGitCommit(arg1:string,arg2:string):Promise<void>;

export function CleanAppCache():Promise<string>;

export function CleanCustomPaths():Promise<string>;

export function CleanTempFiles():Promise<string>;

export function CloneRemoteRepo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateArchive(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function CreateItem(arg1:string,arg2:boolean):Promise<void>;

export function DeleteDriveFile(arg1:string):Promise<void>;

export function DownloadFromDrive(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FileAction(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function GetAvailableLanguages():Promise<Array<string>>;

export function GetCustomModules():Promise<Array<main.CustomModule>>;

export function GetDriveData(arg1:string):Promise<main.RangerState>;

export function GetDrives():Promise<Array<string>>;

export function GetFileAssociations():Promise<Record<string, string>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetGitHistory(arg1:string):Promise<Array<main.GitCommit>>;

export function GetGitHubBranches(arg1:string):Promise<Array<string>>;

export function GetLanguagePack(arg1:string):Promise<Record<string, string>>;

export function GetLocalGitBranches(arg1:string):Promise<Array<string>>;

export function GetOS():Promise<string>;

export function GetRangerData(arg1:string,arg2:boolean):Promise<main.RangerState>;

export function GetSettings():Promise<main.AppSettings>;

export function IsDriveAuthenticated():Promise<boolean>;

export function IsGitInstalled():Promise<boolean>;

export function LoginGoogle(arg1:string,arg2:string):Promise<string>;

export function LogoutGoogle():Promise<void>;

export function OpenAssociationsFile():Promise<void>;

export function OpenFileCustom(arg1:string,arg2:string):Promise<void>;

export function OpenSettingsFile():Promise<void>;

export function OpenTerminal(arg1:string,arg2:string):Promise<void>;

export function ReadFilePreview(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function ScanGitRepos(arg1:string):Promise<Array<main.GitRepo>>;

export function SearchGitHub(arg1:string):Promise<Array<main.RemoteRepo>>;

export function UnzipItem(arg1:string):Promise<void>;
